repos:
-   repo: local
    hooks:
    -   id: flake8
        name: Run flake8
        entry: flake8
        language: python
        types: [python]
    -   id: mypy
        name: Run mypy
        entry: mypy
        language: python
        types: [python]
    -   id: isort
        name: Run isort
        entry: isort
        language: python
        types: [python]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
