all_packages = (
    'general_analytics',
    'simple_bot_settings',
    'bot_stats',
    'command_event',
    'connect_event',
    'error_handler',
    'help_command',
    # 'misc_commands',
    'owner_only',
    'presence_auto_updater',
    # 'application_command_handler',
    'interaction_handler',
    # 'button_command_redirect',
)
