name: Linter
on:
    push:
        paths:
            - '*.py'
    pull_request:
        paths:
            - '*.py'
jobs:
    super-lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        steps:
        -   name: Setup Python
            uses: actions/setup-python@v1
            with:
                python-version: 3.10
                architecture: x64

        -   name: Checkout code
            uses: actions/checkout@v2

        -   name: Run linters
            uses: github/super-linter/slim@v4
            env:
                DEFAULT_BRANCH: rewrite
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                # Run over entire codebase (t) or just new files (f)
                VALIDATE_ALL_CODEBASE: true

                # Give file path
                FILTER_REGEX_INCLUDE: novus/*

                # Specify certain linters
                VALIDATE_PYTHON: true
                VALIDATE_PYTHON_FLAKE8: true
                VALIDATE_PYTHON_ISORT: true
                VALIDATE_PYTHON_MYPY: true
                VALIDATE_PYTHON_PYLINT: true
